Vagrant.configure("2") do |config|
  config.vm.define "ldap" do |ldap|
    ldap.vm.box_download_insecure = true
    ldap.vm.box = "hashicorp/bionic64"
    ldap.vm.network "private_network", ip: "100.0.0.17"
    ldap.vm.synced_folder "./vagrant", "/home/vagrant", disabled: false
	ldap.vm.provision "shell", path: "test.sh"
    ldap.vm.hostname = "ldap"
    ldap.vm.provider "virtualbox" do |v|
      v.name = "ldap"
      v.memory = 2048
      v.cpus = 1
    end
  end
end